export interface ProjectItem {
  title: string;
  category: "saas" | "web" | "mobile";
  categoryLabel: string;
  description: string;
  image: string;
  metric: string;
  bgClass: string;
  iconBg: string;
  textClass: string;
  tags: string[];
  href: string;
}

const rawProjectsList: ProjectItem[] = [
  {
    title: "Clawbot – AI Lead Management",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "An intelligent full-stack AI lead management platform featuring automated sales pipelines and detailed performance dashboards.",
    image: "/saas-showcase.png",
    metric: "Automated Sales Pipelines",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["React.js", "Node.js", "Express", "AI Integration"],
    href: "https://clawbot-ai-lead.vercel.app/login"
  },
  {
    title: "Taxedo: Ride-Hailing Platform",
    category: "web",
    categoryLabel: "Custom Software",
    description: "Engineered a production-ready, custom-built ride-hailing application featuring dynamic pricing engines and live GPS operations.",
    image: "/taxedo.png",
    metric: "Real-time Driver Dispatch",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["PHP", "MVC", "MySQL", "Real-Time GPS"],
    href: "#"
  },
  {
    title: "SchoolFMS - Multi-Tenant SaaS",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "Scalable school management SaaS with tenant-isolated database architecture, role-based access control, and complete finance visibility.",
    image: "/schoolfms.png",
    metric: "Multi-Tenant RBAC Isolation",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["Node.js", "Express", "Prisma", "BullMQ Tasks"],
    href: "https://schoolfms.com/"
  },
  {
    title: "ZorivaPOS – Next-Gen Point of Sale",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "An enterprise-grade point-of-sale system for businesses. Streamlines invoicing, order-taking, and sales operations.",
    image: "/api-showcase.png",
    metric: "Reactive Invoicing Grid",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["React.js", "TypeScript", "Recharts", "Live Inventory"],
    href: "https://pos-frontend-rudu.onrender.com/"
  },
  {
    title: "EduLaunch – Interactive EdTech",
    category: "web",
    categoryLabel: "Web Platform",
    description: "Designed and engineered the official platform for EduLaunch, featuring course pipelines and interactive digital whiteboards.",
    image: "/edulaunch.png",
    metric: "Canvas API Whiteboard",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["Next.js 14", "Canvas API", "Stripe Checkout"],
    href: "https://www.edulaunch.shop/"
  },
  {
    title: "XpertLMS – Centralized Academy",
    category: "web",
    categoryLabel: "MERN Platform",
    description: "A high-performance Learning Management System designed to automate student lifecycles, grading systems, and fee collections.",
    image: "/uiux-showcase.png",
    metric: "1,000+ Enrolled Students",
    bgClass: "bg-[#FCFAF2]",
    iconBg: "bg-[#FAF2CD]",
    textClass: "text-[#b07f18]",
    tags: ["MongoDB", "Express", "React", "Node.js"],
    href: "https://inquisitive-gnome-097562.netlify.app/"
  },
  {
    title: "Stag Chemist - UK Pharmacy Portal",
    category: "web",
    categoryLabel: "E-Commerce",
    description: "UK-based local pharmacy website with React frontend and Firebase backend, featuring admin panels and Stripe payments.",
    image: "/ecommerce-showcase.png",
    metric: "Stripe Checkout & Blog Admin",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["React.js", "Firebase", "Stripe", "Blog Engine"],
    href: "http://stagchemist.com/"
  },
  {
    title: "WearUp – Premium Clothing Store",
    category: "web",
    categoryLabel: "E-Commerce",
    description: "A high-end editorial digital retail platform featuring real-time product queries, interactive shopping carts, and collection cataloging.",
    image: "/web-showcase.png",
    metric: "Editorial Checkout Funnel",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["React.js", "Node.js", "Redux Toolkit", "JWT Secure"],
    href: "https://clothing-frontend-zqt8.onrender.com/"
  },
  {
    title: "AI Interview Simulator",
    category: "web",
    categoryLabel: "AI Web App",
    description: "An AI-powered interview preparation platform that provides real-time simulations and feedback to help users practice.",
    image: "/uiux-showcase.png",
    metric: "Real-time AI Feedback",
    bgClass: "bg-[#FCFAF2]",
    iconBg: "bg-[#FAF2CD]",
    textClass: "text-[#b07f18]",
    tags: ["React.js", "AI Integration", "Tailwind CSS"],
    href: "https://ai-interview-5gz6.vercel.app/"
  },
  {
    title: "Vedic Success – Spiritual Tech",
    category: "web",
    categoryLabel: "Custom Software",
    description: "Spiritual technology interface decoding life through 231 precise parameters using a proprietary VSLR algorithm.",
    image: "/vedic-success.png",
    metric: "VSLR 231-Point Algorithm",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["Next.js", "Algorithms", "Tailwind CSS"],
    href: "https://www.vedicsuccess.com/"
  },
  {
    title: "AGQ - Grievance Mobile App",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "Full-stack grievance mobile application with real-time status sync, queue-driven workflows, and secure lifecycles.",
    image: "/mobile-showcase.png",
    metric: "Citizen/Admin Status Sync",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "Node.js", "Express", "Redis Cache"],
    href: "#"
  },
  {
    title: "Nailify - Beauty Booking App",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "Real-time beauty service booking mobile application with live status, resilient background processing, and auth.",
    image: "/mobile-showcase.png",
    metric: "Live Booking Statuses",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "Node.js", "Express", "BullMQ Jobs"],
    href: "#"
  },
  {
    title: "HerRidez GPS Safety App",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "A production-grade ride tracking platform for women with real-time GPS, SOS safety escalation, and a social layer.",
    image: "/mobile-showcase.png",
    metric: "Real-time GPS Tracking",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "GPS Tracking", "SOS Escalation"],
    href: "#"
  },
  {
    title: "Codsyn - Software House Web",
    category: "web",
    categoryLabel: "Agency Web",
    description: "Official software house site showcasing digital agency capabilities, fluid animations, and highly optimized SEO indexations.",
    image: "/web-showcase.png",
    metric: "100% Core Web Vitals score",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["React.js", "Tailwind CSS", "Framer Motion"],
    href: "https://codsyn.com/"
  },
  {
    title: "Farooq Azam Smart HMS",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "Intelligent medical practice scheduler and secure patient record coordinator automating clinic work routines.",
    image: "/farooq-azam.png",
    metric: "HIPAA Compliant Record Vault",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["React.js", "Firebase Auth", "Firestore DB"],
    href: "#"
  },
  {
    title: "Aura - Mental Health Tracker",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "Biometric stress monitor sync and journal logging mobile app featuring daily mood charts and meditation pipelines.",
    image: "/mobile-showcase.png",
    metric: "Biometric Bluetooth sync",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "BLE Library", "SQLite"],
    href: "#"
  },
  {
    title: "Apex Logistics - Delivery Hub",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "Enterprise fleet coordinator showing active package coordinates, auto route optimization loops, and driver payloads.",
    image: "/saas-showcase.png",
    metric: "Optimized Route Matrix",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["Node.js", "PostgreSQL", "Google Maps API"],
    href: "#"
  },
  {
    title: "CareNet - Telehealth Platform",
    category: "web",
    categoryLabel: "Custom Software",
    description: "WebRTC-driven video sessions connecting verified doctors with remote patients, prescriptions registry, and billing.",
    image: "/web-showcase.png",
    metric: "WebRTC HD video loops",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["Next.js", "Socket.io", "WebRTC", "Stripe"],
    href: "#"
  },
  {
    title: "Dune - Digital Real Estate",
    category: "web",
    categoryLabel: "Web Portal",
    description: "High-end property search directory indexing interactive neighborhood maps, school boundaries, and virtual tours.",
    image: "/uiux-showcase.png",
    metric: "3D Spatial Virtual Tours",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["React.js", "Three.js", "Mapbox GL"],
    href: "#"
  },
  {
    title: "Zenith - Crypto Asset Ledger",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "DeFi dashboard connecting secure wallet keys, tracking token rates, and generating automated tax accounting spreadsheets.",
    image: "/api-showcase.png",
    metric: "Automated Tax Filings",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["Next.js", "Ethers.js", "Tailwind CSS"],
    href: "#"
  },
  {
    title: "QuickServe - POS Restaurant App",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "Tablet-optimized quick dining checkout grid supporting kitchen ticket queue printers and instant table payouts.",
    image: "/mobile-showcase.png",
    metric: "Sub-2s checkout flow",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "ESC/POS", "Redux"],
    href: "#"
  },
  {
    title: "HydroFlow - Smart Grid IoT",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "IoT telemetry system displaying real-time utility flows, leak warnings, and valve metrics.",
    image: "/saas-showcase.png",
    metric: "IoT Sensor Uptime 99.99%",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["Node.js", "MQTT Broker", "TimescaleDB"],
    href: "#"
  },
  {
    title: "EduLink - Student Social App",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "Campus community message boards, class schedule organizers, and peer study group finders.",
    image: "/mobile-showcase.png",
    metric: "20k+ Campus downloads",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "Firebase Auth", "Firestore"],
    href: "#"
  },
  {
    title: "Inverto - Inventory Planner",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "Warehouse stock forecasting utilizing historical sales indicators, demand trends, and automatic reorder alerts.",
    image: "/api-showcase.png",
    metric: "30% Reduction in Stockouts",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["React", "Python", "Flask", "PostgreSQL"],
    href: "#"
  },
  {
    title: "Pulse - Social Analytics Dashboard",
    category: "web",
    categoryLabel: "Web Application",
    description: "Real-time engagement tracker aggregation for social content builders showing follower rate charts and campaign metrics.",
    image: "/web-showcase.png",
    metric: "Sub-50ms Chart Redraws",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["Next.js", "D3.js", "Tailwind CSS"],
    href: "#"
  },
  {
    title: "FitSync - Gym Tracker App",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "Personal training diary, customized exercise logs, and live heart rate monitor integration.",
    image: "/mobile-showcase.png",
    metric: "Wearable Sensor Hookup",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "Apple HealthKit", "Google Fit"],
    href: "#"
  },
  {
    title: "CloudVault - Encrypted Files",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "Zero-knowledge file backup storage indexing metadata values with client-side cryptography.",
    image: "/saas-showcase.png",
    metric: "AES-256 Client Cryptography",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["React", "Node.js", "Web Crypto API", "AWS S3"],
    href: "#"
  },
  {
    title: "LingoBot - AI Language Tutor",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "Conversational language practice engine utilizing LLM integrations to provide speech grammar checks.",
    image: "/mobile-showcase.png",
    metric: "AI speech evaluation loop",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "OpenAI Speech API", "FastAPI"],
    href: "#"
  },
  {
    title: "TaskFlow - Team Kanban Board",
    category: "web",
    categoryLabel: "Web Application",
    description: "Dynamic workspace task tracking showing team member slots, drag-and-drop grids, and notification threads.",
    image: "/web-showcase.png",
    metric: "Real-time board synchronization",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["Next.js", "Socket.io", "React DnD"],
    href: "#"
  },
  {
    title: "EcoLoop - Carbon Footprint Tracker",
    category: "web",
    categoryLabel: "Web Platform",
    description: "Corporate carbon calculation tool auditing shipping receipts, utility invoices, and travel logs to build compliance reports.",
    image: "/web-showcase.png",
    metric: "ISO 14064 Compliance Standards",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["React", "Node.js", "PostgreSQL"],
    href: "#"
  },
  {
    title: "Sentry - Smart Doorbell Monitor",
    category: "mobile",
    categoryLabel: "Mobile App",
    description: "IoT video feeds connecting verified users with home doorbell sensor feeds and push alerts.",
    image: "/mobile-showcase.png",
    metric: "Sub-500ms video start delay",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React Native", "HLS Live stream", "WebRTC"],
    href: "#"
  },
  {
    title: "ProctorAI - Exam Supervision",
    category: "saas",
    categoryLabel: "SaaS Product",
    description: "Intelligent web proctoring tracking gaze coordinates, active user changes, and window focus logs during tests.",
    image: "/saas-showcase.png",
    metric: "98% Fraud Detection Accuracy",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["React", "Webcam API", "Tensorflow.js", "Express"],
    href: "#"
  },
  {
    title: "QBite – Full-Stack Food Delivery Suite",
    category: "saas",
    categoryLabel: "Food Delivery SaaS",
    description: "A premium multi-tenant food delivery suite featuring a high-performance customer ordering portal (sage-gelato), real-time restaurant partner order dashboard (zomato-restaurant), and a centralized administrative control center (zomato-admin).",
    image: "/saas-showcase.png",
    metric: "Multi-Portal Delivery Suite",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["React.js", "Node.js", "Express", "MongoDB", "Redux", "Real-Time Tracking"],
    href: "https://sage-gelato-cb0ebc.netlify.app/"
  },
  {
    title: "LetsCrackEnglish – IELTS/CELPIP Exam Prep",
    category: "web",
    categoryLabel: "EdTech Platform",
    description: "An interactive learning web application designed for students preparing for IELTS and CELPIP exams. Features real-time speaking test recording, full mock test papers, and instant score feedback.",
    image: "/uiux-showcase.png",
    metric: "IELTS & CELPIP Exam Prep",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["React.js", "TypeScript", "Tailwind CSS", "Audio Recording APIs", "Mock Tests"],
    href: "https://letscrackenglish.com/"
  },
  {
    title: "ECONS EXIM Gateway – AI Trade Single-Window",
    category: "saas",
    categoryLabel: "FinTech Trade SaaS",
    description: "An AI-powered single-window commerce gateway in association with the Asian Exporters Chamber of Commerce and Industry (AECCI) to simplify and digitize global trade compliance, escrow payments, and shipment logistics.",
    image: "/saas-showcase.png",
    metric: "AI-Driven EXIM Single-Window",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["React.js", "Node.js", "Express", "AI Compliance Integration", "Escrow Secure Wallet"],
    href: "https://econs.egcindia.in/"
  },
  {
    title: "E8 Productions – Video & Media Solutions",
    category: "web",
    categoryLabel: "Media Agency Site",
    description: "A premium, media-rich portfolio website for E8 Productions, displaying their full-service videography, video editing pipelines, social media growth cases, and original shows.",
    image: "/web-showcase.png",
    metric: "Media & Production Agency",
    bgClass: "bg-[#FCFAF2]",
    iconBg: "bg-[#FAF2CD]",
    textClass: "text-[#b07f18]",
    tags: ["HTML5", "CSS3", "JavaScript", "Video Production", "SEO Optimization"],
    href: "https://www.e8productions.com/"
  },
  {
    title: "Nexa Solutions – Custom Web Development",
    category: "web",
    categoryLabel: "Agency Web Platform",
    description: "Custom web development agency showcase highlighting specialized Shopify integrations, responsive corporate portfolios, WordPress custom templates, and performance-first web apps.",
    image: "/web-showcase.png",
    metric: "Web Design & Development Agency",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["Next.js", "Tailwind CSS", "Shopify", "WordPress", "Custom Software"],
    href: "https://6a169614fc6b422f237ed91c--roaring-peony-2c53a4.netlify.app/"
  },
  {
    title: "Webyapar Solutions – IT Consulting Suite",
    category: "web",
    categoryLabel: "IT Solutions Agency",
    description: "A modern IT consulting and custom software development landing site outlining custom SaaS projects, AI-powered automation workflows, and mobile application engineering services.",
    image: "/web-showcase.png",
    metric: "IT Solutions & Business Migration",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["React.js", "Next.js", "Tailwind CSS", "AI Automation", "Chatbots"],
    href: "https://webyaparsolutions.com/"
  },
  {
    title: "Orbitt Media – Digital Growth Engine",
    category: "web",
    categoryLabel: "Marketing Agency Site",
    description: "A results-oriented digital marketing agency presentation showing SEO frameworks, performance ads (Meta & Google), social media marketing management, and Google Business Profile optimization cases.",
    image: "/uiux-showcase.png",
    metric: "Result-Driven Digital Marketing",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["Next.js", "SEO Optimization", "Branding Systems", "Google & Meta Ads"],
    href: "https://6a1d3c658ef33b4ef0c33620--resilient-cheesecake-fd8dec.netlify.app/"
  },
  {
    title: "Hiranandani Westgate – Real Estate Landing",
    category: "web",
    categoryLabel: "Real Estate Portal",
    description: "High-end luxury real estate presentation page highlighting Thane's premium 25-Acre integrated township, featuring interactive podium amenities lists, detailed tower configurations, and smart location guides.",
    image: "/uiux-showcase.png",
    metric: "Luxury Real Estate Presentation",
    bgClass: "bg-[#FCFAF2]",
    iconBg: "bg-[#FAF2CD]",
    textClass: "text-[#b07f18]",
    tags: ["Next.js", "Tailwind CSS", "Interactive Amenities", "Premium Layout"],
    href: "https://69d79d5d77b5e3567bda1fce--euphonious-lokum-8ffe2b.netlify.app/"
  },
  {
    title: "CIMDR Sangli – DES Educational Portal",
    category: "web",
    categoryLabel: "Educational Institution",
    description: "Chintamanrao Institute of Management Development and Research (CIMDR) website portal containing academic directories, student admission desks, campus placements logs, and NAAC/AICTE accreditation cards.",
    image: "/web-showcase.png",
    metric: "DES Management Institute Portal",
    bgClass: "bg-[#F5FAF9]",
    iconBg: "bg-[#D2EBE7]",
    textClass: "text-[#134D4A]",
    tags: ["Next.js", "Tailwind CSS", "Student Admission Portal", "Placements Desk"],
    href: "https://glittery-kulfi-0fb52f.netlify.app/"
  },
  {
    title: "Car Bazar – Premium Fleet Rentals",
    category: "web",
    categoryLabel: "Rentals Web Platform",
    description: "An immersive car rental platform showcasing premium fleets (SUVs, sedans, luxury cars), featuring sleek GSAP smooth-scrolling animations, custom pointer behaviors, and responsive contact options.",
    image: "/uiux-showcase.png",
    metric: "Premium Car Rental System",
    bgClass: "bg-[#FFF9F5]",
    iconBg: "bg-[#FEEAD9]",
    textClass: "text-brand-orange",
    tags: ["Next.js", "GSAP Animations", "Fleet Management", "Interactive Cursor"],
    href: "https://dancing-cajeta-881cb6.netlify.app/"
  },
  {
    title: "WebCastle UAE – Enterprise Web Studio",
    category: "web",
    categoryLabel: "Web & E-Commerce Agency",
    description: "Enterprise-grade web development and custom software engineering studio showcase illustrating Strapi headless CMS systems, custom Magento builds, and Shopify ecommerce designs.",
    image: "/ecommerce-showcase.png",
    metric: "Enterprise Web Development UAE",
    bgClass: "bg-[#F3F7FD]",
    iconBg: "bg-[#D1E2FB]",
    textClass: "text-[#0c4ca6]",
    tags: ["Next.js", "Strapi Headless CMS", "Magento", "ERP Custom Suite"],
    href: "https://willowy-heliotrope-8af7b2.netlify.app/"
  }
];

const live = rawProjectsList.filter(p => p.href && p.href !== "#");
const inquiry = rawProjectsList.filter(p => !p.href || p.href === "#");

export const projectsList: ProjectItem[] = [
  ...live.slice(0, 10),
  ...inquiry,
  ...live.slice(10)
];
